# Project information
site_name: 'Software Security'
site_description: 'Repo voor SE/NSE 1.4 Software Security: vakinformatie en opgaven per week, voorbeeldcode'
site_url: 'https://hanze-hbo-ict.github.io/sw_sec_docs'
use_directory_urls: false

theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'orange'
  icon:
    logo: 'material/library'
  language: 'nl'
  include_sidebar: false
extra_css:
  - css/extra.css

exclude_docs: |
  /blackboard.md

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: False
      linenums: True
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 3
  - markdown.extensions.def_list
  - markdown.extensions.admonition
  - markdown.extensions.footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed

extra_javascript:
  - js/imgs.js

nav:

plugins:
  - mknotebooks:
      execute: false
